---
- name: deploy and configure prometheus and grafana
  hosts: all
  become: true
  vars:
    alertmanager_web_external_url: "{{ kube_routes['alertmanager'] | default('http://' + ansible_host + ':9093') }}"
    alertmanager_receivers:
      - name: webhook
        webhook_configs:
          - send_resolved: false
            url: http://localhost:5000/webhook
    alertmanager_route:
      group_by: [alertname, cluster, service]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: webhook

    prometheus_alertmanager_config:
      - scheme: http
        static_configs:
          - targets:
              - localhost:9093

    grafana_port: 3000
    grafana_security:
      admin_user: "{{ grafana_admin_user }}"
      admin_password: "{{ grafana_admin_password }}"

    grafana_alerting: {}
    prometheus_web_external_url: "{{ kube_routes['prometheus'] | default('http://' + ansible_host + ':9090') }}"
    grafana_url: "{{ kube_routes['grafana'] | default('http://' + ansible_host + ':' + grafana_port|string) }}"

  tasks:
    - name: install and configure
      ansible.builtin.include_role:
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      loop:
        - prometheus.prometheus.prometheus
        - prometheus.prometheus.alertmanager
        - grafana.grafana.grafana
        - grafana_windows_node

  post_tasks:
    - name: show prometheus dashboard url
      ansible.builtin.debug:
        msg: "prometheus dashboard: {{ prometheus_web_external_url }}"

    - name: show grafana dashboard url
      ansible.builtin.debug:
        msg: "grafana dashboard: {{ grafana_url }}"
