---
- name: set prometheus host
  hosts: "*role_prograf"
  gather_facts: false
  tasks:
    - name: set prometheus ip
      ansible.builtin.add_host:
        name: prometheus
        ansible_host: "{{ ansible_host }}"
        ansible_port: "{{ ansible_port | default('22') }}"

    - name: show prometheus system hostname
      ansible.builtin.debug:
        var: hostvars['prometheus']['ansible_host']

- name: add windows nodes to prometheus
  hosts: "*role_windows"
  gather_facts: false
  vars:
    ansible_port: "{{ hostvars['prometheus']['ansible_port'] | default('22') }}"
  tasks:
    - name: add windows node prometheus
      ansible.builtin.include_role:
        name: prometheus_add_node
        apply:
          delegate_to: "{{ hostvars['prometheus']['ansible_host'] }}"
          connection: ssh
