---

- name: get total size
  win_shell: (Get-WmiObject -Class Win32_logicaldisk).Size
  register: drive_total_size

- name: set total size
  set_fact:
    total_size_before: "{{ ((drive_total_size.stdout_lines[0])|int / (1024*1024*1024)) | round(2, 'floor') }}"

- name: get drive space
  win_shell: Get-PSDrive C | Select-Object Free | ConvertTo-Json
  register: drive_space

- name: set free drive space
  set_fact:
    free_drive_space_before: "{{ ((drive_space.stdout | from_json)['Free']|int / (1024*1024*1024)) | round(2, 'floor') }}"

- debug:
    msg: "free drive space:  {{ free_drive_space_before }} GB ({{ 100 - disk_fullness_percentage|int }}% of total space)"

- block:
    - include_role:
        name: expand-disk-provider
      vars:
        new_disk_size: "{{ total_size_before|int|round + 5 }}"

    - name: expand file system
      win_shell: Resize-Partition -DriveLetter c -Size  (Get-PartitionSupportedSize -DriveLetter c).sizeMax -ErrorAction SilentlyContinue

    - name: get drive space
      win_shell: Get-PSDrive C | Select-Object Free | ConvertTo-Json
      register: drive_space_after_expansion

    - name: set free drive space after expansion
      set_fact:
        free_drive_space_after: "{{ ((drive_space_after_expansion.stdout | from_json)['Free']|int / (1024*1024*1024)) | round(2, 'floor') }}"

    - debug:
        msg: "free drive space:  {{ free_drive_space_after }} GB"
  when: disk_fullness_percentage|int > disk_fullness_percentage_threshold|int