---
- name: create datasource and dashboard
  block:
    - name: create prometheus datasource
      community.grafana.grafana_datasource:
        grafana_url: http://{{ ansible_host }}:{{ aap_metrics_grafana_external_port }}
        grafana_user: "{{ grafana_admin_user }}"
        grafana_password: "{{ grafana_admin_password }}"
        validate_certs: false
        name: Prometheus
        org_id: "1"
        ds_type: prometheus
        ds_url: http://localhost:9090
        access: proxy
        is_default: true
        tls_skip_verify: true

    - name: import dashboards
      ansible.builtin.uri:
        url: http://{{ ansible_host }}:{{ aap_metrics_grafana_external_port }}/api/dashboards/db
        user: "{{ grafana_admin_user }}"
        password: "{{ grafana_admin_password }}"
        method: POST
        status_code: 200
        force_basic_auth: true
        body_format: json
        body: "{{ lookup('file', 'aap_metrics.json') }}"
      register: grafana_dashboard_import
      delegate_to: localhost
      become: false
      changed_when: grafana_dashboard_import.status in [200]
      failed_when: grafana_dashboard_import.status not in [200, 412]
  when:
    - grafana_admin_user is defined
    - grafana_admin_password is defined
