---
- name: expand vm disk to {{ expand_disk_provider_new_disk_size }}
  community.vmware.vmware_guest:
    hostname: "{{ lookup('env', 'VMWARE_HOST') | default(providers.vcenter.hostname) }}"
    username: "{{ lookup('env', 'VMWARE_USER') | default(providers.vcenter.username) }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') | default(providers.vcenter.password) }}"
    validate_certs: false
    name: "{{ config.name }}"
    disk:
      - size_gb: "{{ expand_disk_provider_new_disk_size | int }}"
        autoselect_datastore: true
  delegate_to: localhost
  vars:
    ansible_connection: local
