---
- name: get total disk size
  community.windows.win_disk_facts:

- name: get space details
  block:
    - name: set total size
      ansible.builtin.set_fact:
        total_disk_size: "{{ (_disk.size / 1024 | pow(3)) | round | int }}"

    - name: set free drive space
      ansible.builtin.set_fact:
        free_drive_space: "{{ (_volume.size_remaining / 1024 | pow(3)) | round | int }}"

    - name: show free drive space
      ansible.builtin.debug:
        msg: "free drive space:  {{ free_drive_space }} GB ({{ 100 - expand_disk_windows_disk_fullness_percentage | int }}% of total space)"

  vars:
    _disk: '{{ ansible_facts.disks | selectattr("system_disk") | first }}'
    _partition: "{{ _disk.partitions | selectattr('drive_letter', 'match', 'C') | first }}"
    _volume: "{{ _partition.volumes | first }}"
