---
- name: get total disk size
  ansible.windows.win_shell: (Get-WmiObject -Class Win32_logicaldisk).Size
  register: drive_total_size

- name: set total size
  ansible.builtin.set_fact:
    total_disk_size: "{{ ((drive_total_size.stdout_lines[0]) | int / (1024 * 1024 * 1024)) | round(2, 'floor') }}"

- name: get drive space
  ansible.windows.win_shell: Get-PSDrive C | Select-Object Free | ConvertTo-Json
  register: drive_space

- name: show and set free drive space
  block:
    - name: show free drive space
      ansible.builtin.debug:
        msg: "free drive space:  {{ _free_drive_space }} GB ({{ 100 - _disk_fullness_percentage | int }}% of total space)"

    - name: set free drive space
      ansible.builtin.set_fact:
        free_drive_space: "{{ _free_drive_space }}"
  vars:
    _free_drive_space: "{{ ((drive_space.stdout | from_json)['Free'] | int / (1024 * 1024 * 1024)) | round(2, 'floor') }}"
    _disk_fullness_percentage: "{{ 100 - (100 * (_free_drive_space | int) / (total_disk_size | int)) | int }}"
