---

- name: check to see if .tower.cfg file exists
  stat:
    path: /root/.tower.cfg
  register: tower_cfg_file

- name: fail if file not found
  fail:
    msg: "/root/.tower.cfg is not found"
  when: not tower_cfg_file.stat.exists

- name: get tower config
  slurp:
    src: /root/.tower.cfg
  register: env_file_content
  no_log: true

- name: parse contents
  set_fact:
    tower_env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"
  no_log: true

- name: token not found
  fail:
    msg: "TOWER_OAUTH_TOKEN env variable not found"
  when: (tower_env_vars.TOWER_OAUTH_TOKEN | default(None)) is undefined

